DROP DATABASE IF EXISTS zzj2wtcx84u2ij81;
USE zzj2wtcx84u2ij81;

CREATE TABLE burgers (
id INT AUTO_INCREMENT NOT NULL,
burger_name varchar(255) NOT NULL,
devour BOOLEAN NOT NULL,
createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);